baseurl: "http://irfan3.me" # the subpath of your site, e.g. /blog/

collections:
  page:
    output: true

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
